language: ruby
rvm:
- 2.6.3
before_script: bundle exec rake db:migrate RAILS_ENV=test
before_install:
- gem update --system
- gem install bundler -v 1.17.2
cache: bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
